// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akqadexcidkygqghbtcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrcWFkZXhjaWRreWdxZ2hidGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTk3MDAsImV4cCI6MjA2NDc3NTcwMH0.fQRY0g-gzvgDr5O_EJWnquQjFyybei67iNmgZEz05mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);